# CS2 Benchmark Configuration - Simplified 2-Step Version
metadata:
  game_name: "Counter-Strike 2"
  version: "1.0"
  startup_wait: 35

initial_state: "main_menu"
target_state: "play_menu"  # Just targeting the first transition for now

# Definitions of UI states and their identifying elements
states:
  main_menu:
    description: "CS2 Main Menu with PLAY button"
    required_elements:
      - type: "icon"  # Use specific type "icon" instead of "any"
        text: "PLAY"
        text_match: "contains"
      - type: "icon"  # Also require other menu buttons to be sure
        text: "INVENTORY"
        text_match: "contains"
    timeout: 30

  play_menu:
    description: "Play menu screen with WORKSHOP MAPS"
    required_elements:
      - type: "icon"
        text: "WORKSHOP MAPS"
        text_match: "contains"
    timeout: 20

# State transition definitions
transitions:
  # From main_menu to play_menu
  "main_menu->play_menu":
    action: "click"
    target:
      type: "icon"
      text: "PLAY"
      text_match: "contains"
    expected_delay: 2

# Fallback actions for error recovery
fallbacks:
  general:
    action: "key"
    key: "Escape"
    expected_delay: 1
    max_retries: 3