# CS2 Benchmark Configuration

metadata:
  game_name: "Counter-Strike 2"
  version: "1.0"
  benchmark_duration: 110  # Expected seconds for benchmark to run
  resolution: "1920x1080"  # Target resolution for coordinates
  startup_wait: 30  # Seconds to wait after launching game

initial_state: "main_menu"
target_state: "benchmark_complete"

# Definitions of UI states and their identifying elements
states:
  initial:
    description: "Initial loading state"
    required_elements: []
    timeout: 60  # Allow up to 60 seconds for game to load

  main_menu:
    description: "CS2 Main Menu"
    required_elements:
      - type: "any"
        text: "PLAY"
        text_match: "contains"
    timeout: 30

  play_menu:
    description: "Play menu screen"
    required_elements:
      - type: "any"
        text: "WORKSHOP MAPS"
        text_match: "contains"
    timeout: 20

  workshop_maps:
    description: "Workshop maps selection screen"
    required_elements:
      - type: "any"
        text: "Filter Maps"
        text_match: "contains"
      - type: "any"
        text: "CS2 FPS Bench"
        text_match: "contains"
    timeout: 30

  map_selection:
    description: "Map selection with GO button"
    required_elements:
      - type: "any"
        text: "GO"
        text_match: "exact"
    timeout: 30

  loading_benchmark:
    description: "Loading benchmark map"
    required_elements: []  # This state might not have consistent UI elements
    timeout: 60

  benchmark_running:
    description: "Benchmark is currently running"
    required_elements: []  # The benchmark might not have consistent UI elements to detect
    timeout: 120  # This should be longer than the benchmark duration

  benchmark_complete:
    description: "Benchmark has completed"
    required_elements: []  # The end state might be detected by timeout
    timeout: 10

# State transition definitions
transitions:
  # From main_menu to play_menu
  "main_menu->play_menu":
    action: "click"
    target:
      type: "any"
      text: "PLAY"
      text_match: "contains"
    hardcoded_coords:
      x: 713
      y: 26
    expected_delay: 2

  # From play menu to workshop maps
  "play_menu->workshop_maps":
    action: "click"
    target:
      type: "any"
      text: "WORKSHOP MAPS"
      text_match: "contains"
    hardcoded_coords:
      x: 350
      y: 200
    expected_delay: 3

  # From workshop maps to map selection
  "workshop_maps->map_selection":
    action: "click"
    target:
      type: "any"
      text: "CS2 FPS Bench"
      text_match: "contains"
    expected_delay: 2

  # From map selection to loading benchmark
  "map_selection->loading_benchmark":
    action: "click"
    target:
      type: "any"
      text: "GO"
      text_match: "exact"
    hardcoded_coords:
      x: 500
      y: 300
    expected_delay: 5

  # From loading benchmark to benchmark running
  "loading_benchmark->benchmark_running":
    action: "wait"
    duration: 10  # Wait for benchmark to start
    expected_delay: 10

  # From benchmark running to benchmark complete
  "benchmark_running->benchmark_complete":
    action: "wait"
    duration: 110  # Wait for the benchmark to finish (110 seconds as specified)
    expected_delay: 0

# Fallback actions for error recovery
fallbacks:
  # Generic escape key press as fallback
  general:
    action: "key"
    key: "Escape"
    expected_delay: 1
    max_retries: 3

  # Specific fallback for benchmark screen if it hangs
  benchmark_running:
    action: "key"
    key: "Escape"
    expected_delay: 2
    max_retries: 5